function [r,dr] = fungen_r(theta)
%FUNGEN_R
%    [R,DR] = FUNGEN_R(THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    28-Sep-2022 14:11:55

r = theta.^3-1.0;
if nargout > 1
    dr = theta.^2.*3.0;
end
