function phi = fungen_phi_plot(theta)
%FUNGEN_PHI_PLOT
%    PHI = FUNGEN_PHI_PLOT(THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    28-Sep-2022 14:34:10

t2 = theta.^2;
phi = t2+theta+exp(-t2).*5.0;
