function [r,dr] = fungen2_r(theta)
%FUNGEN2_R
%    [R,DR] = FUNGEN2_R(THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    28-Sep-2022 14:34:10

t2 = theta.^2;
t3 = -t2;
t4 = exp(t3);
r = theta.*2.0-t4.*theta.*1.0e+1+1.0;
if nargout > 1
    dr = t4.*-1.0e+1+t2.*t4.*2.0e+1+2.0;
end
