function [F,dF] = implicitRHS(in1,x1,u1)
%implicitRHS
%    [F,dF] = implicitRHS(IN1,X1,U1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    07-Oct-2022 19:09:56

dx1 = in1(1,:);
z1 = in1(2,:);
t2 = tanh(dx1);
t3 = u1.*2.0;
t4 = -z1;
t5 = t3+t4;
t6 = tanh(t5);
F = [dx1+t2+u1+x1.*z1;t4+t6];
if nargout > 1
    dF = reshape([-t2.^2+2.0,0.0,x1,t6.^2-2.0],[2,2]);
end
